### ISSUE TITLE
[Brasil] Developer Angular Pleno

### ISSUE THREAD

**Issue by patriciastite** [seujobtech/vagas#369]
**Sobre a empresa**
É uma consultoria de inovação tecnológica com uma equipe altamente qualificada focada em ajudar empresas a acelerar para a transformação digital.

**Requisitos Obrigatórios:**
4 anos de experiência com Angular;
Nível de inglês avançado.

Desejável ter trabalhado com Java.

**Benefícios:**
Plano de Saúde 
Plano Odontológico
Vale transporte 
Vale refeição 
SESC

Sobre a Posição:
CLT
100% remoto
Nível de senioridade pleno

Está dentro do perfil?
Candidate-se aqui https://jobs.quickin.io/rhf/jobs/631252c7505f640015b1798e

**Comment by Recrutadora** [comment]
Vaga top!

**Comment by patriciastite** [comment]
> Vaga top!

link de cadastro no descritivo
