### ISSUE TITLE
[Homeoffice] Backend Developer na Voll

### ISSUE THREAD

**Issue by marcusocosta** [seujobtech/vagas#38]
A VOLL nasceu para simplificar a mobilidade corporativa com uma solução única e global. 
Acreditamos em um ambiente de negócios fértil para transformar o mundo e, para que isto aconteça, é fundamental que as pessoas se encontrem!
Para a vaga de Pessoa desenvolvedora backend procuramos um profissional que desenvolva NodeJS, GraphQL e Microserviços que se sinta confortavel com o trabalho em equipe.

Responsabilidades e atribuições

• Desenvolver softwares focados em escalabilidade e performance;
• Escrever códigos eficientes, reutilizáveis e de fácil manutenção;
• Participar de discussões em busca de soluções com os times de UX, Back-end e Front-end;
• Escrever testes (unit, integration, component, contract, end-to-end)

Requisitos e qualificações

Bons conhecimentos em Node.js
Testes automatizados
Microserviços/Serverless
AWS
BD Relacional: MySQL
BD Não-Relacional: MongoDB

**Comment by obetomuniz** [comment]
Olá @marcusocosta, valeu por compartilhar sua vaga :D Poderia informar o metodo de aplicação para a mesma e demais informações exigidas pelo nosso template? Assim que atualizar ela, reabrimos
